name: Auto-Add Issues & PRs to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Add Issue or PR to GitHub Project
        uses: actions/add-to-project@v1.1.0
        with:
          project-id: "PVT_kwDOBaFPkM4A17Eb"
          github-token: ${{ steps.get-token.outputs.token }}
