name: Auto-add Issues & PRs to Project

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add Issue or PR to Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/synnada-ai/projects/5/views/1
          github-token: ${{ secrets.GITHUB_TOKEN }}