name: Move Issues to Done When Closed

on:
  issues:
    types: [closed]

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App Token
        id: get-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Move Issue to "Done"
        uses: actions/add-to-project@v1.0.2
        with:
          project-id: "PVT_kwDOBaFPkM4A17Eb"
          project-url: https://github.com/orgs/synnada-ai/projects/5
          github-token: ${{ steps.get-token.outputs.token }}
          status: "Done"