name: Publish to PyPI

on:
  release:
    types: [published]  # Triggers when a release is published

jobs:
  build-and-publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.12']
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install wheel twine setuptools

      - name: Build Linux wheel
        if: matrix.os == 'ubuntu-latest'
        run: |
          python3.12 setup.py bdist_wheel --plat-name manylinux1_x86_64 --python-tag cp312

      - name: Build macOS ARM64 wheel
        if: matrix.os == 'macos-latest'
        run: |
          python3.12 setup.py bdist_wheel --plat-name macosx_14_0_arm64 --python-tag cp312

      - name: Publish to PyPI
        if: github.event_name == 'release' && github.event.action == 'published'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*